apiVersion: apps/v1
kind: Deployment
metadata:
  name: zooz

spec:
  replicas: 3

  selector:
    matchLabels:
      app: my-web-app
  
  template:
    metadata:
      name: my-web-app
      labels:
        app: my-web-app
    spec:
      containers:
        - name: nginx-container
          image: zeyadmedhat/nginx-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
  